version: 2.1

orbs:
  clojure: lambdaisland/clojure@0.0.7

jobs:
  build:
    executor: clojure/openjdk8
    steps:
      - checkout
      - clojure/with_cache:
          steps:
            - run: clojure -Xdev:test
